name: Semgrep SAST Scan
on: [push, pull_request]
jobs:
  sast:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Install Semgrep
        run: |
          pip install semgrep
      - name: Run Semgrep Scan
        run: |
          semgrep --config=auto --json > semgrep-results.json
      - name: Upload Semgrep Results
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-results
          path: semgrep-results.json
